name: virtual_coop
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.3
  rxdart: ^0.27.1
  flutter_svg: ^0.22.0
  encrypt: ^5.0.0
  font_awesome_flutter: ^9.1.0
  http: ^0.12.2
  shared_preferences: ^2.0.6
  local_auth: ^1.1.6
  screenshot: ^1.2.3
  esys_flutter_share: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0
  flutter_native_splash : 
  
flutter:

  uses-material-design: true

  assets:
    #Assets Imagenes
    - assets/img/
    - assets/logosVirtualCoop/
    - assets/logosVirtualCoopLasNaves/
    - assets/logosVirtualCoopSolAndes/
    - assets/logosVirtualCoopCiudadZamora/
    - assets/logosVirtualCoopCCStoDomingo/
    - assets/logosVirtualCoopChunchi/
    - assets/logosVirtualCoopCoacPichincha/
    - assets/logosVirtualCoopJPMora/
    - assets/logosVirtualCoopDev/

    #Assets Config
    - configApp/
  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf
